SELECT CONCAT('ALTER TABLE `', TABLE_NAME, '` ADD CONSTRAINT ', CONSTRAINT_NAME, ' FOREIGN KEY(', COLUMN_NAME, ') REFERENCES `', REFERENCED_TABLE_NAME, '`(', REFERENCED_COLUMN_NAME, ');')
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE CONSTRAINT_NAME LIKE 'FK%'
AND CONSTRAINT_SCHEMA = DATABASE();